BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01116';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01117';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00057';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00058';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00059';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00060';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00061';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00062';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00913';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00914';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00915';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00916';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00917';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00918';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00919';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00920';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00923';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON IBIZA' WHERE serial = '01088';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PASAMANOS BAÑERA HAWAII' WHERE serial = '1196-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 140X78' WHERE serial = '00009';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '0003-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MILENIUM 182X123' WHERE serial = '0195';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TERRANOVA 183X113' WHERE serial = '00585';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00921';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00922';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X5.3 BRILLANTE' WHERE serial = '00924';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '0000';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1253-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1253-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X90X42' WHERE serial = '00109';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X100' WHERE serial = '00248';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X100' WHERE serial = '00683';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BALI' WHERE serial = '1223-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA MALTA 160X80' WHERE serial = '1281-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS DERECHA 152X75' WHERE serial = '0003-2';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ITALIANA ECO 140X70' WHERE serial = '00172';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS DERECHA 152X75' WHERE serial = '0003-3';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU DERECHA 180X120' WHERE serial = '00948';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CALIMA 152X80 SIN ANTIDESLIZANTE' WHERE serial = '00457';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA MATE' WHERE serial = '1238-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA MATE' WHERE serial = '1239-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA SECADORA 50X40 MATE' WHERE serial = '00813';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 MATE' WHERE serial = '00859';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 MATE' WHERE serial = '00868';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 MATE' WHERE serial = '00872';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 MATE' WHERE serial = '0864';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 MATE' WHERE serial = '01086';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 MATE' WHERE serial = '01126';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 MATE' WHERE serial = '1099';
UPDATE public.moldes SET nombre_articulo = 'MOLDE REPISA LAVAMANOS 63X20 MATE' WHERE serial = '00834';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TAPA EXTENSION 60CM MATE' WHERE serial = '10652';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TAPA EXTENSION 60CM MATE' WHERE serial = '10501';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SAHARA 48X41 MATE' WHERE serial = '00829';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 MATE' WHERE serial = '01082';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 MATE' WHERE serial = '01085';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 MATE' WHERE serial = '01075';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 MATE' WHERE serial = '01076';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '1182-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '1185-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '1186-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '00762';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '1185-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE REGISTRO INSPECCION 65X45 MATE' WHERE serial = '00840';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 MATE' WHERE serial = '1132';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 MATE' WHERE serial = '01064';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 MATE' WHERE serial = '01067';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '00808';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 MATE' WHERE serial = '00715';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 MATE' WHERE serial = '1205-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X55' WHERE serial = '00663';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE DUCHA 80X80 MATE' WHERE serial = '01073';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE  DUCHA 90X90 MATE' WHERE serial = '00861';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 MATE' WHERE serial = '01106';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 MATE' WHERE serial = '01107';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 MATE' WHERE serial = '00805';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 MATE' WHERE serial = '00801';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 MATE' WHERE serial = '1242-4';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 MATE SIN PERF' WHERE serial = '00978';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 MATE' WHERE serial = '1140';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 MATE' WHERE serial = '01105';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 MATE' WHERE serial = '01108';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '107-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '107-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0055';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '107-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '107-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '00893';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '107-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-08';
COMMIT;