BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE' WHERE serial = '222-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE' WHERE serial = '223-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE' WHERE serial = '223-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS MECA VESSEL 35X35 SOFT MATE' WHERE serial = '223-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '231-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE' WHERE serial = '225-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-49';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 79X48' WHERE serial = '0171-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-37';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 155X48' WHERE serial = '215-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-53';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 94X48' WHERE serial = '0187-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1199-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESA DE TRABAJO PRO-MESON 140X60' WHERE serial = '0181-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '0067-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 124X48' WHERE serial = '0185-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1232-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 94X48 BRILLANTE' WHERE serial = '206-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 BRILLANTE' WHERE serial = '1205-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 94X48 BRILLANTE' WHERE serial = '206-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-51';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS PRO 46X36' WHERE serial = '0178-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA TAHITI 152X152' WHERE serial = '0167-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-33';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-50';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DOHA VESSEL 45X33 SOFT MATE' WHERE serial = '225-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS DERECHA 152X75' WHERE serial = '0003-1';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS DERECHA 152X75' WHERE serial = '0003-4';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS PRO 46X36' WHERE serial = '0178-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MOBU 200' WHERE serial = '0028-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-05';
COMMIT;