BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SAHARA 47.5X40.5 SOFT MATE' WHERE serial = '00719';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '01012';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X56 BRILLANTE' WHERE serial = '00862';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SAHARA 47.5X40.5 BRILLANTE' WHERE serial = '00701';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '00991';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '01006';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '01009';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '01023';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '1001024';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE' WHERE serial = '01135';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '1181-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '1250-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '0078-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '0078-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 79X56 BRILLANTE' WHERE serial = '00325';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '01091';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE' WHERE serial = '00342';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X56 BRILLANTE' WHERE serial = '00518';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 79X56 BRILLANTE' WHERE serial = '00246';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 79X56 BRILLANTE' WHERE serial = '00242';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X56 BRILLANTE' WHERE serial = '05181';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE' WHERE serial = '00365';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE' WHERE serial = '00541';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE' WHERE serial = '00700';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 48X43 BRILLANTE' WHERE serial = '00454';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE' WHERE serial = '00647';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE' WHERE serial = '00344';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE' WHERE serial = '00743';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OCEAN 48X43 BRILLANTE' WHERE serial = '00455';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE' WHERE serial = '00718';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE' WHERE serial = '00698';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X56 BRILLANTE' WHERE serial = '00869';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 94X56 BRILLANTE' WHERE serial = '00860';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X56 BRILLANTE' WHERE serial = '00681';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '01072';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '0069-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '0069-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '0069-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '0069-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '00138';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '00858';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '0173';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1231-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1232-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE' WHERE serial = '0181';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1230-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1229-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1225-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1227-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1228-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1224-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1226-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00166';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00291';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00682';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00447';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '01070';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00444';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00299';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '01069';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00092';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '00335';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00448';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00178';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00445';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00293';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '0067-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00179';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00098';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '00323';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '0067-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '0067-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '0066-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '1240-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '01071';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE' WHERE serial = '01110';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE' WHERE serial = '01111';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE' WHERE serial = '01112';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '01090';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE' WHERE serial = '01109';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE' WHERE serial = '01089';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS CORAL 41X37 BRILLANTE' WHERE serial = '00497';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS CORAL 41X37 BRILLANTE' WHERE serial = '00477';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS CORAL 41X37 BRILLANTE' WHERE serial = '00492';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS CORAL 41X37 BRILLANTE' WHERE serial = '00475';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS CORAL 41X37 BRILLANTE' WHERE serial = '00493';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ANKARA 43X43 BRILLANTE' WHERE serial = '0733';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS CORAL 41X37 BRILLANTE' WHERE serial = '00495';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00986';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ANKARA 43X43 BRILLANTE' WHERE serial = '00741';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00985';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00981';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00982';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00980';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00966';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00968';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00979';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00965';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '00967';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-25';
COMMIT;