BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLACA MUESTRAS' WHERE serial = '230-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLACA PARA MUESTRAS 20X20 CM' WHERE serial = '230-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0196-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01152';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-60';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESA DE TRABAJO PRO-MESON 140X60' WHERE serial = '0181-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0196-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01149';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1232-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01147';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01148';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1232-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE' WHERE serial = '1232-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-48';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-46';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-45';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-32';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-30';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-31';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-29';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-28';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1278';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-27';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-25';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-42';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '1160-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '1160-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '1160-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '1160-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 155X48' WHERE serial = '215-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-41';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '1160-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-36';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-39';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-38';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-35';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-33';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0186-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-31';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-31';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '01036';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-13';
COMMIT;