BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1202';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '1240-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '1240';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1199-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE SALPICADERO 150X55' WHERE serial = '214-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - SIN PERF' WHERE serial = '1206-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE SALPICADERO 180X55' WHERE serial = '211-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 94X48' WHERE serial = '204-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 94X48' WHERE serial = '0195-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0196-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 94X48' WHERE serial = '0195-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 94X48' WHERE serial = '0195-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLACA GENOVA 124X48' WHERE serial = '0189-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLACA GENOVA 124X48' WHERE serial = '0189-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLACA GENOVA 124X48' WHERE serial = '0189-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-3';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLACA GENOVA 124X48' WHERE serial = '0189-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 124X48' WHERE serial = '0185-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESA DE TRABAJO PRO-MESON 140X60' WHERE serial = '0181-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS PRO 46X36' WHERE serial = '0178-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS PRO 46X36' WHERE serial = '0178-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 79X48' WHERE serial = '0176-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 79X48' WHERE serial = '0176-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 79X48' WHERE serial = '0176-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 79X48' WHERE serial = '0176-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO 60X60' WHERE serial = '0172-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 79X48' WHERE serial = '0171-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 100X50' WHERE serial = '0170-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 100X50' WHERE serial = '0170-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '753-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MUESTRA COLORES' WHERE serial = '0169-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MUESTRA COLORES' WHERE serial = '0169-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0753';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 120X51' WHERE serial = '0166-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '1155-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0782';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '01159';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 100X50' WHERE serial = '0164-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 120X51' WHERE serial = '0166-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 100X50' WHERE serial = '0164-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB' WHERE serial = '0142-4';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '00954';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '01068';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB' WHERE serial = '0142-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '1261-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0153-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '1240-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '1257-02';
COMMIT;