BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '01034';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '00953';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '00956';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ITALIANA ECO 150X70' WHERE serial = '00983';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE GALAPAGOS 250X200 V.2' WHERE serial = '207-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA SANTORINI 180X180' WHERE serial = '0191-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON CATALUÑA' WHERE serial = '0155-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA SANTORINI 180X180 V.2' WHERE serial = '212-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1292-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON CATALUÑA' WHERE serial = '0155-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ESPAÑOLA 152X75' WHERE serial = '00318';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ESPAÑOLA 152X75' WHERE serial = '00607';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU IZQUIERDA 180X120' WHERE serial = '0032-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 160X90' WHERE serial = '0011-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BONAIRE 183X152' WHERE serial = '0023-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS V.2' WHERE serial = '1274-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1277-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1276-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA HONOLULU DERECHA' WHERE serial = '1062';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON SANTORINI PLUS 180x80' WHERE serial = '232-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MYDAS EMPOTRAR 182' WHERE serial = '228-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE NORUEGA 156' WHERE serial = '00431';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA MALTA 160X80' WHERE serial = '1289-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1295-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1296-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1285-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON CATALUÑA' WHERE serial = '1297-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON SANTORINI PLUS 180x80' WHERE serial = '232-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE QATAR 180X100' WHERE serial = '1283';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON DANESA' WHERE serial = '01059';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON CATALUÑA' WHERE serial = '0155-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X90X42' WHERE serial = '00429';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X90X42' WHERE serial = '00738';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA NORUEGA' WHERE serial = '1192-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE NORUEGA 156' WHERE serial = '00430';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA NORUEGA' WHERE serial = '1192-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS V.2' WHERE serial = '1279-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA HONOLULU IZQUIERDA' WHERE serial = '971';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON TAHITI 152X152' WHERE serial = '0165-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON QATAR 180X100' WHERE serial = '1195-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS V.2' WHERE serial = '1283-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1253-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1275-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1294-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8X4 RTM' WHERE serial = '1260';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-8';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CHATTANOOGAN 200X200' WHERE serial = '00054';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU IZQUIERDA 180X120' WHERE serial = '01062';
UPDATE public.moldes SET nombre_articulo = 'MOLDE IBIZA 182X123' WHERE serial = '01087';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CHALLENGER 190X190' WHERE serial = '00049';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU DERECHA 180X120' WHERE serial = '01061';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '0004-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '0004-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '0004-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE DANESA 189X113X45' WHERE serial = '00043';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS IZQUIERDA 152X75' WHERE serial = '0004-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS IZQUIERDA 152X75' WHERE serial = '0004-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS IZQUIERDA 152X75' WHERE serial = '0004-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ITALIANA ECO 140X70' WHERE serial = '00023';
UPDATE public.moldes SET nombre_articulo = 'MOLDE SAVANNA 170X80X40' WHERE serial = '00002';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '0004-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '0004-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '0003-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 140X78' WHERE serial = '00008';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '0120-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MYDAS EMPOTRAR 182' WHERE serial = '228-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS EN L' WHERE serial = '0173-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VIVE 60X50' WHERE serial = '208-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA HONOLULU IZQUIERDA' WHERE serial = '1300-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 181X123' WHERE serial = '00234';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 160X90' WHERE serial = '00036';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA MALTA' WHERE serial = '1282-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON MILENIUM LARGO' WHERE serial = '00958';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON MILENIUM CORTO' WHERE serial = '00963';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CHATTANOOGAN 200X200' WHERE serial = '1278-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 181X123' WHERE serial = '00678';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA HONOLULU DERECHA' WHERE serial = '1293-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '0003-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 157X78' WHERE serial = '00411';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 157X78' WHERE serial = '00413';
COMMIT;