BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-26';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '1247';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-28';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '1244';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '1245';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '1246';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-30';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-29';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01021';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01025';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01030';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01018';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01005';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01010';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '01015';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '00988';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '00989';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS PETIT 38X38 BRILLANTE' WHERE serial = '00817';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE' WHERE serial = '00987';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MENTA 84X51 BRILLANTE' WHERE serial = '00633';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MENTA 84X51 BRILLANTE' WHERE serial = '00750';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS PETIT 38X38 BRILLANTE' WHERE serial = '00159';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MANZANO 84X56 BRILLANTE' WHERE serial = '00699';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MANZANO 84X56 BRILLANTE' WHERE serial = '00727';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MANZANO 84X56 BRILLANTE' WHERE serial = '00723';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X56 BRILLANTE' WHERE serial = '00885';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE' WHERE serial = '00992';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE' WHERE serial = '00993';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE' WHERE serial = '00994';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X56 BRILLANTE' WHERE serial = '00880';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS EMBASSY 100X51 BRILLANTE' WHERE serial = '00802';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE' WHERE serial = '00936';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE' WHERE serial = '00942';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE' WHERE serial = '00951';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CEREZO 81X45 BRILLANTE' WHERE serial = '00730';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS EMBASSY 100X51 BRILLANTE' WHERE serial = '00803';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CARRARA 50X51 BRILLANTE' WHERE serial = '00108';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CEREZO 81X45 BRILLANTE' WHERE serial = '00710';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CARRARA 50X51 BRILLANTE' WHERE serial = '00113';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CARRARA 50X51 BRILLANTE' WHERE serial = '00110';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CARAMELO 81X45 BRILLANTE' WHERE serial = '1280-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CANELO 55X43 BRILLANTE' WHERE serial = '00726';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CARAMELO 81X45 BRILLANTE' WHERE serial = '00708';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CARAMELO 81X45 BRILLANTE' WHERE serial = '00734';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CANELO 55X43 BRILLANTE' WHERE serial = '00711';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS ESPIGA 79X45 BRILLANTE' WHERE serial = '00716';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CANELO 55X43 BRILLANTE' WHERE serial = '00724';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE DUCHA 152X76 BRILLANTE' WHERE serial = '0690-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE DUCHA 152X76 BRILLANTE' WHERE serial = '0693-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE DUCHA 152X76 BRILLANTE' WHERE serial = '0694-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X55' WHERE serial = '0035-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE DUCHA 90X109 BRILLANTE' WHERE serial = '00251';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DE DUCHA 152X76 BRILLANTE' WHERE serial = '00695';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X55' WHERE serial = '01007';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X55' WHERE serial = '0035-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CIPRES 62X48' WHERE serial = '10472';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CIPRES 62X48' WHERE serial = '10473';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CIPRES 62X48' WHERE serial = '10474';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CIPRES 62X48' WHERE serial = '01028';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS CIPRES 62X48' WHERE serial = '10471';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-32';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '00944';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-27';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00955';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00892';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON 100X51 BRILLANTE' WHERE serial = '1045';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON 100X51 BRILLANTE' WHERE serial = '1176-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON 100X51 BRILLANTE' WHERE serial = '1044';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON 100X51 BRILLANTE' WHERE serial = '01046';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON 100X51 BRILLANTE' WHERE serial = '1177-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON 100X51 BRILLANTE' WHERE serial = '01060';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 MATE SIN PERF' WHERE serial = '00945';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 100X51 MATE' WHERE serial = '01045';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01031';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00895';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE' WHERE serial = '00470';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE' WHERE serial = '00185';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE' WHERE serial = '00637';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01017';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01022';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01032';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE' WHERE serial = '00144';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01029';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01020';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01013';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01008';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '01035';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '00990';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE' WHERE serial = '01004';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '00959';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '00974';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE' WHERE serial = '01033';
COMMIT;