BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X55' WHERE serial = '01037';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X55' WHERE serial = '01066';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 130X78' WHERE serial = '0006';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 130X78' WHERE serial = '0007';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 148X90' WHERE serial = '00019';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA 148X90' WHERE serial = '00020';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '00279';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '00592';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '00736';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '00737';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '00284';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '00315';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '00452';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '00593';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS RTM DERECHA 153X78' WHERE serial = '00878';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS RTM DERECHA 153X78' WHERE serial = '08781';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS RTM IZQUIERDA 153X78' WHERE serial = '08792';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS RTM IZQUIERDA 153X78' WHERE serial = '08791';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '00451';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS DERECHA 153X78' WHERE serial = '00280';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS IZQUIERDA 153X78' WHERE serial = '0004-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA BALI' WHERE serial = '1210-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS V.2' WHERE serial = '1306-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CALIMA 152X80 CON ANTIDESLIZANTE' WHERE serial = '00586';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CALIMA 152X80 SIN ANTIDESLIZANTE' WHERE serial = '00644';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CALIMA 152X80 CON ANTIDESLIZANTE' WHERE serial = '180-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ARRECIFE 152X90' WHERE serial = '00458';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ARRECIFE 183X90' WHERE serial = '00616';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BONAIRE 183X152' WHERE serial = '00239';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARU 152X152' WHERE serial = '00241';
UPDATE public.moldes SET nombre_articulo = 'MOLDE DELTA 150X150' WHERE serial = '00051';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ESPAÑOLA 152X75' WHERE serial = '00026';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ESPAÑOLA 170X75' WHERE serial = '00115';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ESPAÑOLA 170X75' WHERE serial = '00030';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ESPAÑOLA 170X75' WHERE serial = '00031';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CHALLENGER 190X190' WHERE serial = '0028-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CHALLENGER 190X190' WHERE serial = '0028-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CHALLENGER 190X190' WHERE serial = '1258-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE DELTA 130X130' WHERE serial = '00739';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '00970';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '1285-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '1286-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS EN L' WHERE serial = '0173-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '00940';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '00046';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON AMERICANA PLUS' WHERE serial = '09701';
UPDATE public.moldes SET nombre_articulo = 'MOLDE QATAR 180X100' WHERE serial = '1194-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE QATAR 180X100' WHERE serial = '0135-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA MALTA' WHERE serial = '1290-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA HONOLULU IZQUIERDA' WHERE serial = '1061';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON BAÑERA HONOLULU DERECHA' WHERE serial = '952';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HEXAGONA 216X69' WHERE serial = '00001';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HAWAI ESQUINERA 150X150' WHERE serial = '00003';
UPDATE public.moldes SET nombre_articulo = 'MOLDE GALAPAGOS 250X200' WHERE serial = '1235-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 160X90' WHERE serial = '00321';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 160X90' WHERE serial = '00322';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X100' WHERE serial = '00039';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FRANCESA 180X90X42' WHERE serial = '00732';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU IZQUIERDA 180X120' WHERE serial = '0032-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU IZQUIERDA 180X120' WHERE serial = '1256-2';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU IZQUIERDA 180X120' WHERE serial = '00964';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO RTM 150X8.5  BRILLANTE' WHERE serial = '1180-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE JAMAICA PLUS IZQUIERDA 152X75' WHERE serial = '0005-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE IBIZA 182X123' WHERE serial = '01088';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00941';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00943';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00947';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00949';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00925';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00926';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00927';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00928';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00929';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00937';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8 PLANO RTM' WHERE serial = '1094-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8 PLANO RTM' WHERE serial = '1095-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 150X8 PLANO RTM' WHERE serial = '1096-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00938';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X8.5 BRILLANTE' WHERE serial = '00939';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01172';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01121';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01122';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01123';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01124';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01163';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01164';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01115';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01118';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01119';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01120';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X10 BRILLANTE' WHERE serial = '00056';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01165';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01166';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01167';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01168';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01170';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01171';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01169';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01113';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ZOCALO 122X6 BRILLANTE' WHERE serial = '01114';
COMMIT;