BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-35';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE' WHERE serial = '225-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1199-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE IBIZA 182X100' WHERE serial = '229-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE IBIZA 182X100' WHERE serial = '229-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE' WHERE serial = '225-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO IZQUIERDO 100X60' WHERE serial = '0179-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 55X50' WHERE serial = '226-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-46';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-48';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-40';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-39';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-45';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA SANTORINI 180X180 V.2' WHERE serial = '212-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-58';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-47';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '01092';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 BRILLANTE' WHERE serial = '0088-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 BRILLANTE' WHERE serial = '0088-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 BRILLANTE' WHERE serial = '0088-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 70X60' WHERE serial = '1189-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-42';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-71';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-68';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-59';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-55';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-67';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-72';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-25';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS PRO 46X36' WHERE serial = '0178-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE' WHERE serial = '0067-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-64';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-74';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '210-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 124x48' WHERE serial = '0182-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-34';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-38';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-70';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-49';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-57';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '0066-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB' WHERE serial = '1206-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '1252-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 79X48' WHERE serial = '0171-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-43';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-52';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2' WHERE serial = '213-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '231-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO DERECHO 100X60' WHERE serial = '201-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 70X60' WHERE serial = '1191-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 63X51 1 BOWL' WHERE serial = '0197-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '210-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '231-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE' WHERE serial = '222-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-04';
COMMIT;