BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS PRO 46X36' WHERE serial = '0178-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '01149';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-52';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-50';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-34';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01152';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01153';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00975';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-31';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-51';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 55X50' WHERE serial = '226-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-43';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '01147';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '1160-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-31';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-35';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '978';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '00976';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-53';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01154';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '1160-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-44';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-40';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-32';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-28';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 BRILLANTE' WHERE serial = '0088-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 79X48 BRILLANTE' WHERE serial = '1193-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB' WHERE serial = '0142-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-26';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE' WHERE serial = '225-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-27';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1161-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-40';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-25';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-25';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-56';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-60';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-54';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-30';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-37';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-36';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-34';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-66';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-62';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-47';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-73';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '1213-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-63';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-65';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-61';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-43';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X43' WHERE serial = '0175-41';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 90X60 BRILLANTE' WHERE serial = '0088-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO DERECHO 140X60' WHERE serial = '200-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '00954';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '1160-09';
COMMIT;