BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE SALPICADERO 61X10 PARA LVM' WHERE serial = '1220-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AMATISTA' WHERE serial = '1243-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS AMATISTA' WHERE serial = '1246-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS QUADRATTO 66X51 SIN SALPICADERO' WHERE serial = '1219-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 151X60' WHERE serial = '1221-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE SALPICADERO 151X60' WHERE serial = '1222-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB' WHERE serial = '0142-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PISO DUCHA 115X70' WHERE serial = '1209-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1201-3';
UPDATE public.moldes SET nombre_articulo = 'MOLDE COCINA MURANO 210X60 BRILLANTE' WHERE serial = '1208-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1201-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1204-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1199-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 63X48 BRILLANTE' WHERE serial = '1200-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TAPA REGISTRO 30X30 BRILLANTE' WHERE serial = '00835';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TAPA REGISTRO 30X30 BRILLANTE' WHERE serial = '00836';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 79X48 BRILLANTE' WHERE serial = '1193-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS VENECIA 63X48 BRILLANTE' WHERE serial = '1233-2';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TAPA REGISTRO 30X30 BRILLANTE' WHERE serial = '00826';
UPDATE public.moldes SET nombre_articulo = 'MOLDE TAPA REGISTRO 30X30 BRILLANTE' WHERE serial = '00827';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON LAVAMANOS OASIS 63X48 SOFT MATE' WHERE serial = '222-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE' WHERE serial = '223-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE' WHERE serial = '222-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 70X60' WHERE serial = '1190-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA MATE' WHERE serial = '00876';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 80X60' WHERE serial = '0107-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 60X51 MATE' WHERE serial = '00080';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 48X60' WHERE serial = '0104-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 MATE' WHERE serial = '1155-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 60X51 MATE' WHERE serial = '1299-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 MATE' WHERE serial = '00753';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 MATE' WHERE serial = '00782';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS VENECIA 63X48 BRILLANTE' WHERE serial = '1233-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GAS MULTIPLE 53X15 BRILLANTE' WHERE serial = '1237-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS VENECIA 63X48 BRILLANTE' WHERE serial = '1175-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GAS MULTIPLE 53X15 BRILLANTE' WHERE serial = '00890';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GAS MULTIPLE 53X15 BRILLANTE' WHERE serial = '1236-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA LLAVE GAS 17X17 BRILLANTE' WHERE serial = '00014';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA LLAVE GAS 17X17 BRILLANTE' WHERE serial = '01016';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA LLAVE GAS 17X17 BRILLANTE' WHERE serial = '01001';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA BRILLANTE' WHERE serial = '00865';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA BRILLANTE' WHERE serial = '00875';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA BRILLANTE' WHERE serial = '00887';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA LLAVE GAS 17X17 BRILLANTE' WHERE serial = '01011';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00882';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA BRILLANTE' WHERE serial = '00866';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO NEVERA BRILLANTE' WHERE serial = '00871';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00897';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00874';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00877';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00156';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00859';
UPDATE public.moldes SET nombre_articulo = 'MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE' WHERE serial = '00864';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01146';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS ECO 30X30' WHERE serial = '01057';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS ECO 30X30' WHERE serial = '01058';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01145';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01142';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01143';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01144';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 BRILLANTE' WHERE serial = '1204-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '01074';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 BRILLANTE' WHERE serial = '1205-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 BRILLANTE' WHERE serial = '1203-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 60X51 BRILLANTE' WHERE serial = '00487';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 BRILLANTE' WHERE serial = '00740';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS 46X46 BRILLANTE' WHERE serial = '00536';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '00898';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 46X51 BRILLANTE' WHERE serial = '0091-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 60X51 BRILLANTE' WHERE serial = '00486';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '00899';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 46X51 BRILLANTE' WHERE serial = '0091-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 46X51 BRILLANTE' WHERE serial = '00720';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 46X51 BRILLANTE' WHERE serial = '00188';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '00896';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 46X51 BRILLANTE' WHERE serial = '00189';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 46X51 BRILLANTE' WHERE serial = '00117';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE' WHERE serial = '01054';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE' WHERE serial = '01055';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE' WHERE serial = '01056';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE' WHERE serial = '00933';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE' WHERE serial = '00931';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE' WHERE serial = '00950';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1241-7';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1249-8';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1185-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1242';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1178';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1183-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '1184-02';
COMMIT;