BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 MATE SIN PERF' WHERE serial = '00944';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-49';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-28';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01150';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 155X48' WHERE serial = '215-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '00901';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-37';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-29';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-21';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-39';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-54';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '01155';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-47';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-36';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '0954';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-26';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-55';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1218';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-39';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-33';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 79x48' WHERE serial = '0184-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS JOHAN VESSEL 50X40 BRILLANTE' WHERE serial = '230-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-37';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-38';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-20';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-48';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-36';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-29';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-69';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01151';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-30';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-35';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-40';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '00902';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-27';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-16';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-32';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 55X50' WHERE serial = '226-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01148';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '1269-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE SIN PERF' WHERE serial = '1160-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-34';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '1243-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-44';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-45';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-26';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 155X48' WHERE serial = '215-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-42';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-46';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 55X50' WHERE serial = '226-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 40X30' WHERE serial = '202-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 55X50' WHERE serial = '226-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-25';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-22';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-24';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-18';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE' WHERE serial = '0081-07';
COMMIT;