BEGIN;
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-19';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 48X38' WHERE serial = '0177-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 94X48' WHERE serial = '0188-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 180X60 PERF-CUB V.2' WHERE serial = '209-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '00900';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '1259-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 124X48' WHERE serial = '0185-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 94X48' WHERE serial = '0195-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO IZQUIERDO 100X60' WHERE serial = '0179-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS VERSA 50X50 BRILLANTE' WHERE serial = '219-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '231-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '231-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 94X48' WHERE serial = '0195-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00977';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 46X51' WHERE serial = '0124-41';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 124X48' WHERE serial = '0183-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 63X48' WHERE serial = '0192-15';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 94X48' WHERE serial = '204-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 94X48' WHERE serial = '0187-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 60X60' WHERE serial = '0106-33';
UPDATE public.moldes SET nombre_articulo = 'MOLDE DANESA 189X113X45' WHERE serial = '1305-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1253-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS PRO IZQUIERDO 140X60' WHERE serial = '0174-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 63X48' WHERE serial = '0163-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 48X43' WHERE serial = '205-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1253-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA CATALUÑA 170X90' WHERE serial = '1253-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS ECO 70X60' WHERE serial = '1188-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 80X60 BRILLANTE' WHERE serial = '0087-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU DERECHA 180X120' WHERE serial = '1291-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-23';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '1251-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 48X60 BRILLANTE' WHERE serial = '0085-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE' WHERE serial = '0089-12';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS PARMA 79X48 BRILLANTE' WHERE serial = '1193-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 50X50 BRILLANTE' WHERE serial = '0168-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0196-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '01093';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0196-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE' WHERE serial = '222-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE HONOLULU IZQUIERDA 180X120' WHERE serial = '1298-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MILENIUM 182X123' WHERE serial = '00456';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS OSLO 79X48' WHERE serial = '0190-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA' WHERE serial = '216-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '1207-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00895';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '00873';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS AQUA 60X60 BRILLANTE' WHERE serial = '0086-17';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE' WHERE serial = '223-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-44';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 124x48' WHERE serial = '0182-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAPLATOS KOA 84X56' WHERE serial = '0180-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESA DE TRABAJO PRO-MESON 140X60' WHERE serial = '0181-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ITALIANA ECO 150X70' WHERE serial = '00022';
UPDATE public.moldes SET nombre_articulo = 'MOLDE ITALIANA ECO 150X70' WHERE serial = '00984';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BARRA COCINA 120X55 BRILLANTE - SIN PERF' WHERE serial = '1206-02';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 94X48' WHERE serial = '0196-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS RIO 48X43 BRILLANTE' WHERE serial = '1249-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE AMERICANA PLUS V.2' WHERE serial = '1287-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE FALDON CATALUÑA' WHERE serial = '1254-01';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS SIENA 63x48' WHERE serial = '0194-25';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS BARI 79X48 BRILLANTE' WHERE serial = '0066-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS GENOVA 63X48' WHERE serial = '0193-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVAMANOS ECO 48X38' WHERE serial = '0062-75';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-11';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 - PERF-CUB' WHERE serial = '231-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-14';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON ECO 120X55 BRILLANTE' WHERE serial = '1162-13';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 79X48' WHERE serial = '0176-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE BAÑERA SANTORINI 180X180 V.2' WHERE serial = '212-03';
UPDATE public.moldes SET nombre_articulo = 'MOLDE LAVARROPAS 48X51W BRILLANTE' WHERE serial = '01155';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-09';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-08';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 79X48' WHERE serial = '0176-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-06';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-10';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-05';
UPDATE public.moldes SET nombre_articulo = 'MOLDE PLAQUITA PARA LVM GENOVA 63X48' WHERE serial = '218-07';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB' WHERE serial = '227-04';
UPDATE public.moldes SET nombre_articulo = 'MOLDE MESON COCINA 150X60 V.2 SIN PERF' WHERE serial = '210-09';
COMMIT;