BEGIN;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS ECO 40X30', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON ECO 150X55 MATE SIN PERF', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS ECO 46X51', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS 48X51W BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 155X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON ECO 120X55 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS ECO 60X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON ECO 150X55 BRILLANTE SIN PERF', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 60X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SIENA 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SIENA 79X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 48X38', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS JOHAN VESSEL 50X40 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 80X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS ECO 48X38', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS VERSA 55X50', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS BARI 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVATRAPEROS PRO 46X36', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS ECO 80X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 48X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 48X43', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA 180X60 PERF-CUB V.2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 90X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS PARMA 79X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS PRO DERECHO 140X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS GENOVA 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS KOA 84X56', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS PARMA 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE IBIZA 182X100', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS PRO IZQUIERDO 100X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BAÑERA SANTORINI 180X180 V.2', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS BARI 79X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS ECO 70X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS ECO 48X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 79X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA 150X60 V.2 - PERF-CUB', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SIENA 124X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS KOA 63X51 1 BOWL', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS 50X50 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS VERSA 50X50 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS RIO 48X43 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS GENOVA 79X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS PRO DERECHO 100X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA 150X60 V.2 SIN PERF', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS MECA VESSEL 35X35 SOFT MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS PRO 60X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS GENOVA 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SIENA 48X43', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESA DE TRABAJO PRO-MESON 140X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS GENOVA 124X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 94X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVATRAPEROS 46X46 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BAÑERA TAHITI 152X152', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS DOHA VESSEL 45X33 SOFT MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE JAMAICA PLUS DERECHA 152X75', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MOBU 200', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 124X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS BARI 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE DANESA 189X113X45', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BAÑERA CATALUÑA 170X90', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS PRO IZQUIERDO 140X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE HONOLULU DERECHA 180X120', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SIENA 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE HONOLULU IZQUIERDA 180X120', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO IBIZA 182X123', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MILENIUM 182X123', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ITALIANA ECO 150X70', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BARRA COCINA 120X55 BRILLANTE - SIN PERF', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA PLUS V.2', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON CATALUÑA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 79X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PLACA MUESTRAS', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PLACA PARA MUESTRAS 20X20 CM', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS OSLO 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO BARRA COCINA 120X55 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS ECO 48X38', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE SALPICADERO 150X55', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE SALPICADERO 180X55', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PLACA GENOVA 124X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS BARI 100X50', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MUESTRA COLORES', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SIENA 120X51', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OSLO 100X50', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE SALPICADERO 61X10 PARA LVM', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS AMATISTA', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 66X51 SIN SALPICADERO', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA 151X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE SALPICADERO 151X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PISO DUCHA 115X70', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE COCINA MURANO 210X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE TAPA REGISTRO 30X30 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS VENECIA 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON LAVAMANOS OASIS 63X48 SOFT MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA GRIFO NEVERA MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS 60X51 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS 50X50 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA GAS MULTIPLE 53X15 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA LLAVE GAS 17X17 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA GRIFO NEVERA BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVATRAPEROS ECO 30X30', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS 60X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS 46X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE REPISA LAVAMANOS 63X20 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE REPISA LAVAMANOS 48X20 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SAHARA 47.5X40.5 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SAHARA 47.5X40.5 SOFT MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 79X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OCEAN 79X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OCEAN 63X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS OCEAN 48X43 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 94X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 63X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS CORAL 41X37 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS ANKARA 43X43 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS PETIT 38X38 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS MENTA 84X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS MANZANO 84X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS LAUREL 63X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS EMBASSY 100X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS CEREZO 81X45 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS CARRARA 50X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS CARAMELO 81X45 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS CANELO 55X43 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS ESPIGA 79X45 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PISO DE DUCHA 152X76 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON COCINA 180X55', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PISO DE DUCHA 90X109 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS CIPRES 62X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON 100X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MESON ECO 100X51 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO IBIZA 182X100', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON COCINA AQUA 150X60 V3 PERF CUBIERTA', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE GALAPAGOS 250X200 V.2', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BAÑERA SANTORINI 180X180', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON COCINA 150X60 V.2 - PERF-CUB', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ESPAÑOLA 152X75', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS VIVE 60X50', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FRANCESA 160X90', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BONAIRE 183X152', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO 150X8X4 RTM', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON BAÑERA HONOLULU DERECHA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS SIENA 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON SANTORINI PLUS 180X80', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE MYDAS EMPOTRAR 182', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE NORUEGA 156', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BAÑERA MALTA 160X80', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE QATAR 180X100', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON DANESA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FRANCESA 180X90X42', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON BAÑERA NORUEGA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON BAÑERA HONOLULU IZQUIERDA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON TAHITI 152X152', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON QATAR 180X100', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO FALDON SANTORINI PLUS 180X80', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CHATTANOOGAN 200X200', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE IBIZA 182X123', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CHALLENGER 190X190', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA PLUS IZQUIERDA 153X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA PLUS DERECHA 153X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE JAMAICA PLUS IZQUIERDA 152X75', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ITALIANA ECO 140X70', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE SAVANNA 170X80X40', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA 140X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON ECO 120X55 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON COCINA 180X60 SIN PERF V2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO PLACA PARA ENSAYOS 30X20 CM', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO  LAVAMANOS GENOVA 124X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON AMERICANA PLUS', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON AMERICANA PLUS EN L', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON COCINA RTM 180X60 V.2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO SALPICADERO 180X60 V.2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO SALPICADERO 150X60 V.2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS SIENA 155X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS GENOVA 155X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS IGUAZU 40X28', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVATRAPEROS ECO 30X30', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MYDAS 182', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FRANCESA 181X123', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON BAÑERA MALTA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON COCINA VERSA 150X55  SIN PERF CUB', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 94X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 79X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO  PLAQUITA PARA LVM GENOVA 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON MILENIUM LARGO', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON MILENIUM CORTO', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON COCINA 180X60 PERF-CUB V.2', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO  LAVAPLATOS KOA 63X51 1 BOWL', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MEDIA ESFERA', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS GENOVA 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS VERSA 55X50', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS AQUA 60X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS AQUA 80X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS AQUA 90X60 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS AQUA 48X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LVM BARI 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA 157X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA 130X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA 148X90', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA PLUS RTM DERECHA 153X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE AMERICANA PLUS RTM IZQUIERDA 153X78', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BAÑERA BALI', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CALIMA 152X80 CON ANTIDESLIZANTE', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CALIMA 152X80 SIN ANTIDESLIZANTE', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ARRECIFE 152X90', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ARRECIFE 183X90', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE BARU 152X152', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE DELTA 150X150', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ESPAÑOLA 170X75', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE DELTA 130X130', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE HEXAGONA 216X69', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE HAWAI ESQUINERA 150X150', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE GALAPAGOS 250X200', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FRANCESA 180X100', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO RTM 150X8.5  BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO 122X8.5 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO 150X8 PLANO RTM', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO 122X6 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO 122X10 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE ZOCALO 122X5.3 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON IBIZA', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PASAMANOS BAÑERA HAWAII', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE TERRANOVA 183X113', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE FALDON BALI', 'FV') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA SECADORA 50X40 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE CAJA GRIFO LAVADORA 30X21 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 60X60 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE REPISA LAVAMANOS 63X20 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE TAPA EXTENSION 60CM MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVAMANOS SAHARA 48X41 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 80X60 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVATRAPEROS AQUA 40X35 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE REGISTRO INSPECCION 65X45 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVATRAPEROS 46X46 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS ECO 60X55', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PISO DE DUCHA 80X80 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE PISO DE  DUCHA 90X90 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 48X60 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MOLDE LAVARROPAS AQUA 90X60 MATE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS DOHA VESSEL 45X33', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS TRENTINO 63X48 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS MECA VESSEL 35X35', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO MESON LAVAMANOS OASIS 63X48', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS VERSA 50X50 BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS 48X51W BRILLANTE', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVATRAPEROS PRO 46X36', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVARROPAS AQUA 60X60', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS OSLO 48X43', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS OSLO 48X38', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta) VALUES ('MODELO LAVAMANOS OSLO 124X48', 'MS') ON CONFLICT DO NOTHING;
COMMIT;

