
-- SQL script to create the movements table
create table if not exists public.movimientos_materia_prima (
  id bigint generated by default as identity primary key,
  materia_prima_id text, 
  materia_prima_nombre text,
  materia_prima_codigo text,
  unidad_texto text,
  tipo text, -- Entradas, Salidas, Pendiente, Solicitud de traslado
  concepto text, -- Ajuste de inventario, Abastecimiento, Molde nuevo, Reparación
  molde_asociado_id bigint references public.moldes(id),
  observaciones text,
  created_at timestamp with time zone default now(),
  created_by text
);
