BEGIN;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS ECO 40X30', 'Marmol_sintetico', 'GEN-B5F9EBF6') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 150X55 MATE SIN PERF', 'Marmol_sintetico', 'GEN-32EA413A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 46X51', 'Marmol_sintetico', 'GEN-25DE4202') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 48X51W BRILLANTE', 'Marmol_sintetico', 'GEN-2410127A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 155X48', 'Marmol_sintetico', 'GEN-DED85F3B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 120X55 BRILLANTE', 'Marmol_sintetico', 'GEN-F5C4D16D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 60X60', 'Marmol_sintetico', 'GEN-18909648') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-67CFEA39') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 150X55 BRILLANTE SIN PERF', 'Marmol_sintetico', 'GEN-BE7B9884') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 94X48', 'Marmol_sintetico', 'GEN-080E9A38') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 60X60 BRILLANTE', 'Marmol_sintetico', 'GEN-13464072') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 63x48', 'Marmol_sintetico', 'GEN-907AAC67') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 79x48', 'Marmol_sintetico', 'GEN-0E8C45AD') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 48X38', 'Marmol_sintetico', 'GEN-3B85B384') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA', 'Marmol_sintetico', 'GEN-FA82F2C8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS JOHAN VESSEL 50X40 BRILLANTE', 'Marmol_sintetico', 'GEN-3D421B00') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 80X60 BRILLANTE', 'Marmol_sintetico', 'GEN-024DFD0E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS ECO 48X38', 'Marmol_sintetico', 'GEN-15147FF7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS VERSA 55X50', 'Marmol_sintetico', 'GEN-29F6AE6A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 63X48', 'Marmol_sintetico', 'GEN-41CFA414') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 63X48', 'Marmol_sintetico', 'GEN-3E21E4D9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS PRO 46X36', 'Marmol_sintetico', 'GEN-096C7882') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 80X60', 'Marmol_sintetico', 'GEN-BA8A864B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 48X60 BRILLANTE', 'Marmol_sintetico', 'GEN-9AE39C8D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 48X43', 'Marmol_sintetico', 'GEN-FBB82086') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 180X60 PERF-CUB V.2', 'Marmol_sintetico', 'GEN-10E79286') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 90X60 BRILLANTE', 'Marmol_sintetico', 'GEN-1DD15D3B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS PARMA 79X48 BRILLANTE', 'Marmol_sintetico', 'GEN-76643797') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB', 'Marmol_sintetico', 'GEN-C277087E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE', 'Marmol_sintetico', 'GEN-BB20216C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE', 'Marmol_sintetico', 'GEN-14EAC080') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO DERECHO 140X60', 'Marmol_sintetico', 'GEN-EF90BF13') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 63X48', 'Marmol_sintetico', 'GEN-2038485D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS KOA 84X56', 'Marmol_sintetico', 'GEN-E6441216') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS PARMA 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-E058778F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE IBIZA 182X100', 'Marmol_sintetico', 'GEN-AD033E6C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO IZQUIERDO 100X60', 'Marmol_sintetico', 'GEN-8B2CB990') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA SANTORINI 180X180 V.2', 'Fibra_de_vidrio', 'GEN-26F0CE61') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 79X48 BRILLANTE', 'Marmol_sintetico', 'GEN-3F0FA96F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2', 'Marmol_sintetico', 'GEN-24A4410E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 70X60', 'Marmol_sintetico', 'GEN-0A47DA8E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 48X60', 'Marmol_sintetico', 'GEN-6F5F9E90') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE', 'Marmol_sintetico', 'GEN-EBBB7DA8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 79X48', 'Marmol_sintetico', 'GEN-ED4BF6DE') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 150X60 V.2 - PERF-CUB', 'Marmol_sintetico', 'GEN-DD50705E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 124x48', 'Marmol_sintetico', 'GEN-6B9F83B6') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS KOA 63X51 1 BOWL', 'Marmol_sintetico', 'GEN-C4E98CBA') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 50X50 BRILLANTE', 'Marmol_sintetico', 'GEN-AA2DFB47') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS VERSA 50X50 BRILLANTE', 'Marmol_sintetico', 'GEN-F6BCF50C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS RIO 48X43 BRILLANTE', 'Marmol_sintetico', 'GEN-46E986E8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 79X48', 'Marmol_sintetico', 'GEN-9768F44F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO DERECHO 100X60', 'Marmol_sintetico', 'GEN-D2449A1D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 150X60 V.2 SIN PERF', 'Marmol_sintetico', 'GEN-583A057E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-4DEB718D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE', 'Marmol_sintetico', 'GEN-8F89D031') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS MECA VESSEL 35X35 SOFT MATE', 'Marmol_sintetico', 'GEN-EC9DADE7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO 60X60', 'Marmol_sintetico', 'GEN-7D9D6774') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 94X48', 'Marmol_sintetico', 'GEN-3CA90E03') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 48X43', 'Marmol_sintetico', 'GEN-58EE3363') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESA DE TRABAJO PRO-MESON 140X60', 'Marmol_sintetico', 'GEN-05EA2334') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 124X48', 'Marmol_sintetico', 'GEN-9A04DADF') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-43E97C84') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 94X48 BRILLANTE', 'Marmol_sintetico', 'GEN-8E3F9E86') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS 46X46 BRILLANTE', 'Marmol_sintetico', 'GEN-5057AAD1') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA TAHITI 152X152', 'Fibra_de_vidrio', 'GEN-62E52E23') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS DOHA VESSEL 45X33 SOFT MATE', 'Marmol_sintetico', 'GEN-A99AE44E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE JAMAICA PLUS DERECHA 152X75', 'Fibra_de_vidrio', 'GEN-EB5A7C47') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MOBU 200', 'Fibra_de_vidrio', 'GEN-A4A36C7A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 124X48', 'Marmol_sintetico', 'GEN-0BB01749') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 94X48', 'Marmol_sintetico', 'GEN-F136CC99') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 94X48', 'Marmol_sintetico', 'GEN-F5754F30') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE DANESA 189X113X45', 'Fibra_de_vidrio', 'GEN-242DB4DA') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA CATALUÑA 170X90', 'Fibra_de_vidrio', 'GEN-F431C7AD') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO IZQUIERDO 140X60', 'Marmol_sintetico', 'GEN-75D00D9B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HONOLULU DERECHA 180X120', 'Fibra_de_vidrio', 'GEN-17A864E1') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 94X48', 'Marmol_sintetico', 'GEN-4313A476') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HONOLULU IZQUIERDA 180X120', 'Fibra_de_vidrio', 'GEN-E27D77B4') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO IBIZA 182X123', 'Marmol_sintetico', 'GEN-8480E740') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MILENIUM 182X123', 'Fibra_de_vidrio', 'GEN-342ACE25') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 63X48', 'Marmol_sintetico', 'GEN-67AE484C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ITALIANA ECO 150X70', 'Fibra_de_vidrio', 'GEN-9C13F155') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BARRA COCINA 120X55 BRILLANTE - SIN PERF', 'Marmol_sintetico', 'GEN-919BAFBE') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS V.2', 'Fibra_de_vidrio', 'GEN-8DEAFA1D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON CATALUÑA', 'Fibra_de_vidrio', 'GEN-3DB66B38') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB', 'Marmol_sintetico', 'GEN-CF763137') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 79X48', 'Marmol_sintetico', 'GEN-9B6F5A5A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLACA MUESTRAS', 'Marmol_sintetico', 'GEN-1CDA4FD6') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLACA PARA MUESTRAS 20X20 CM', 'Marmol_sintetico', 'GEN-A8C6A218') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 94X48', 'Marmol_sintetico', 'GEN-B0AD66AF') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO BARRA COCINA 120X55 BRILLANTE', 'Marmol_sintetico', 'GEN-8664D10E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS ECO 48X38', 'Marmol_sintetico', 'GEN-6092739D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE', 'Marmol_sintetico', 'GEN-80B61AAF') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 150X55', 'Marmol_sintetico', 'GEN-369A3FD0') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 180X55', 'Marmol_sintetico', 'GEN-3C2C304D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLACA GENOVA 124X48', 'Marmol_sintetico', 'GEN-5FCD6123') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 100X50', 'Marmol_sintetico', 'GEN-F969B1C6') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MUESTRA COLORES', 'Marmol_sintetico', 'GEN-4B324890') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 120X51', 'Marmol_sintetico', 'GEN-D9B45766') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 100X50', 'Marmol_sintetico', 'GEN-18855A36') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 61X10 PARA LVM', 'Marmol_sintetico', 'GEN-917175B8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS AMATISTA', 'Marmol_sintetico', 'GEN-21FE07CE') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 66X51 SIN SALPICADERO', 'Marmol_sintetico', 'GEN-F488ADBC') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 151X60', 'Marmol_sintetico', 'GEN-33E12E1F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 151X60', 'Marmol_sintetico', 'GEN-9F4BBB03') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DUCHA 115X70', 'Marmol_sintetico', 'GEN-9D72C211') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE COCINA MURANO 210X60 BRILLANTE', 'Marmol_sintetico', 'GEN-7AC1D18E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE TAPA REGISTRO 30X30 BRILLANTE', 'Marmol_sintetico', 'GEN-B2C145F9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS VENECIA 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-E5F97E23') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON LAVAMANOS OASIS 63X48 SOFT MATE', 'Marmol_sintetico', 'GEN-641B3809') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO NEVERA MATE', 'Marmol_sintetico', 'GEN-101F1FB0') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 60X51 MATE', 'Marmol_sintetico', 'GEN-E3C1E7A0') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 50X50 MATE', 'Marmol_sintetico', 'GEN-26E6A12A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GAS MULTIPLE 53X15 BRILLANTE', 'Marmol_sintetico', 'GEN-9F12DAD8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA LLAVE GAS 17X17 BRILLANTE', 'Marmol_sintetico', 'GEN-B329B9F8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO NEVERA BRILLANTE', 'Marmol_sintetico', 'GEN-6D8B71EC') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE', 'Marmol_sintetico', 'GEN-B61E8A38') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS ECO 30X30', 'Marmol_sintetico', 'GEN-85C48732') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 60X51 BRILLANTE', 'Marmol_sintetico', 'GEN-C3FD3EBF') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 46X51 BRILLANTE', 'Marmol_sintetico', 'GEN-B865EE78') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE', 'Marmol_sintetico', 'GEN-2A2F652E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REPISA LAVAMANOS 63X20 BRILLANTE', 'Marmol_sintetico', 'GEN-2D9F2C67') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REPISA LAVAMANOS 48X20 BRILLANTE', 'Marmol_sintetico', 'GEN-D536AE2A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SAHARA 47.5X40.5 BRILLANTE', 'Marmol_sintetico', 'GEN-7705E3F4') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SAHARA 47.5X40.5 SOFT MATE', 'Marmol_sintetico', 'GEN-2C98C3A9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE', 'Marmol_sintetico', 'GEN-60B2A03D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 79X56 BRILLANTE', 'Marmol_sintetico', 'GEN-E871F6C2') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 79X56 BRILLANTE', 'Marmol_sintetico', 'GEN-735F6F6D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-15298E68') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 63X56 BRILLANTE', 'Marmol_sintetico', 'GEN-74ECA95A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE', 'Marmol_sintetico', 'GEN-D51FA0F7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 48X43 BRILLANTE', 'Marmol_sintetico', 'GEN-586E7FB7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 94X56 BRILLANTE', 'Marmol_sintetico', 'GEN-1972A2BB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 63X56 BRILLANTE', 'Marmol_sintetico', 'GEN-2D54CEE7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE', 'Marmol_sintetico', 'GEN-5533492C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-91E35663') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS CORAL 41X37 BRILLANTE', 'Marmol_sintetico', 'GEN-9E7A27D0') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS ANKARA 43X43 BRILLANTE', 'Marmol_sintetico', 'GEN-3090F068') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE', 'Marmol_sintetico', 'GEN-583B74E7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS PETIT 38X38 BRILLANTE', 'Marmol_sintetico', 'GEN-C11357F4') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS MENTA 84X51 BRILLANTE', 'Marmol_sintetico', 'GEN-DCD23D17') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS MANZANO 84X56 BRILLANTE', 'Marmol_sintetico', 'GEN-52F2A1C3') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS LAUREL 63X56 BRILLANTE', 'Marmol_sintetico', 'GEN-712A2C5A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE', 'Marmol_sintetico', 'GEN-F0AFCD8F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS EMBASSY 100X51 BRILLANTE', 'Marmol_sintetico', 'GEN-7F74C841') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CEREZO 81X45 BRILLANTE', 'Marmol_sintetico', 'GEN-11247F1C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CARRARA 50X51 BRILLANTE', 'Marmol_sintetico', 'GEN-E27E70C3') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CARAMELO 81X45 BRILLANTE', 'Marmol_sintetico', 'GEN-7DF4C895') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CANELO 55X43 BRILLANTE', 'Marmol_sintetico', 'GEN-9C578490') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS ESPIGA 79X45 BRILLANTE', 'Marmol_sintetico', 'GEN-49DB69E5') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE DUCHA 152X76 BRILLANTE', 'Marmol_sintetico', 'GEN-213E4734') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 180X55', 'Marmol_sintetico', 'GEN-90DDE7C1') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE DUCHA 90X109 BRILLANTE', 'Marmol_sintetico', 'GEN-0E7CDBEC') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CIPRES 62X48', 'Marmol_sintetico', 'GEN-00AF8FD5') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON 100X51 BRILLANTE', 'Marmol_sintetico', 'GEN-2DD257C7') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 100X51 MATE', 'Marmol_sintetico', 'GEN-673150B3') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE', 'Marmol_sintetico', 'GEN-F1D8A739') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE', 'Marmol_sintetico', 'GEN-A050AE9C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO IBIZA 182X100', 'Marmol_sintetico', 'GEN-740123EE') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA AQUA 150X60 V3 PERF CUBIERTA', 'Marmol_sintetico', 'GEN-58F79AD8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE GALAPAGOS 250X200 V.2', 'Fibra_de_vidrio', 'GEN-0A1DB8C9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA SANTORINI 180X180', 'Fibra_de_vidrio', 'GEN-5CBF83EB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA 150X60 V.2 - PERF-CUB', 'Marmol_sintetico', 'GEN-0D4DC76D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ESPAÑOLA 152X75', 'Fibra_de_vidrio', 'GEN-DCF00A9B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS VIVE 60X50', 'Marmol_sintetico', 'GEN-ECFEBCEE') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 160X90', 'Fibra_de_vidrio', 'GEN-E64B192B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BONAIRE 183X152', 'Fibra_de_vidrio', 'GEN-48AD6010') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 150X8X4 RTM', 'Marmol_sintetico', 'GEN-CB45EA3F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA HONOLULU DERECHA', 'Fibra_de_vidrio', 'GEN-1E47360B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS SIENA 94X48', 'Marmol_sintetico', 'GEN-800FA688') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 63X48', 'Marmol_sintetico', 'GEN-5D80EBC8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON SANTORINI PLUS 180x80', 'Marmol_sintetico', 'GEN-31E05F43') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MYDAS EMPOTRAR 182', 'Marmol_sintetico', 'GEN-9C24EB5E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE NORUEGA 156', 'Fibra_de_vidrio', 'GEN-357DA65C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA MALTA 160X80', 'Fibra_de_vidrio', 'GEN-B7957BD1') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE QATAR 180X100', 'Fibra_de_vidrio', 'GEN-F10792DA') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON DANESA', 'Fibra_de_vidrio', 'GEN-192E414E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 180X90X42', 'Fibra_de_vidrio', 'GEN-BEC0CF6D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA NORUEGA', 'Fibra_de_vidrio', 'GEN-904A9C6C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA HONOLULU IZQUIERDA', 'Fibra_de_vidrio', 'GEN-C8BD56E2') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON TAHITI 152X152', 'Fibra_de_vidrio', 'GEN-83A6DA35') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON QATAR 180X100', 'Fibra_de_vidrio', 'GEN-C8F907F9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO FALDON SANTORINI PLUS 180x80', 'Fibra_de_vidrio', 'GEN-34E7DCA9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CHATTANOOGAN 200X200', 'Fibra_de_vidrio', 'GEN-2A4F4DFE') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE IBIZA 182X123', 'Fibra_de_vidrio', 'GEN-48CC3670') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CHALLENGER 190X190', 'Fibra_de_vidrio', 'GEN-A93CD6BA') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS IZQUIERDA 153X78', 'Fibra_de_vidrio', 'GEN-802A5F05') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS DERECHA 153X78', 'Fibra_de_vidrio', 'GEN-B120BCDF') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE JAMAICA PLUS IZQUIERDA 152X75', 'Fibra_de_vidrio', 'GEN-60F88056') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ITALIANA ECO 140X70', 'Fibra_de_vidrio', 'GEN-842E7B9A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SAVANNA 170X80X40', 'Fibra_de_vidrio', 'GEN-406585CA') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 140X78', 'Fibra_de_vidrio', 'GEN-8AAF53FB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON ECO 120X55 BRILLANTE', 'Marmol_sintetico', 'GEN-254B9850') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA 180X60 SIN PERF V2', 'Marmol_sintetico', 'GEN-9E4960F1') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLACA PARA ENSAYOS 30X20 CM', 'Marmol_sintetico', 'GEN-11FD21D8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO  LAVAMANOS GENOVA 124X48', 'Marmol_sintetico', 'GEN-85245432') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON AMERICANA PLUS', 'Fibra_de_vidrio', 'GEN-CCCF5157') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON AMERICANA PLUS EN L', 'Fibra_de_vidrio', 'GEN-A81C8E59') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA RTM 180X60 V.2', 'Marmol_sintetico', 'GEN-3B72E758') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO SALPICADERO 180X60 V.2', 'Marmol_sintetico', 'GEN-CA193B71') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO SALPICADERO 150X60 V.2', 'Marmol_sintetico', 'GEN-2A5B61C2') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS SIENA 155x48', 'Marmol_sintetico', 'GEN-02512B65') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS GENOVA 155x48', 'Marmol_sintetico', 'GEN-2B001C7C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS IGUAZU 40X28', 'Marmol_sintetico', 'GEN-FF67A28B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVATRAPEROS ECO 30X30', 'Marmol_sintetico', 'GEN-B9BEA65A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MYDAS 182', 'Fibra_de_vidrio', 'GEN-E9989681') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 181X123', 'Fibra_de_vidrio', 'GEN-6C7C92F3') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA MALTA', 'Fibra_de_vidrio', 'GEN-3D404415') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA VERSA 150X55  SIN PERF CUB', 'Marmol_sintetico', 'GEN-8B8B12BB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 94X48', 'Marmol_sintetico', 'GEN-3CD41B06') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 79X48', 'Marmol_sintetico', 'GEN-0CC92E9A') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO  PLAQUITA PARA LVM GENOVA 63X48', 'Marmol_sintetico', 'GEN-557D2B09') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON MILENIUM LARGO', 'Fibra_de_vidrio', 'GEN-D28430BB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON MILENIUM CORTO', 'Fibra_de_vidrio', 'GEN-B43A8DA6') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA 180X60 PERF-CUB V.2', 'Marmol_sintetico', 'GEN-51ED8E36') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO  LAVAPLATOS KOA 63X51 1 BOWL', 'Marmol_sintetico', 'GEN-0CC5852B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MEDIA ESFERA', 'Marmol_sintetico', 'GEN-423149C9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS GENOVA 63X48', 'Marmol_sintetico', 'GEN-9E7A165D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS VERSA 55X50', 'Marmol_sintetico', 'GEN-278678BB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 60X60 BRILLANTE', 'Marmol_sintetico', 'GEN-B7373B71') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 80X60 BRILLANTE', 'Marmol_sintetico', 'GEN-421A7076') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 90X60 BRILLANTE', 'Marmol_sintetico', 'GEN-FB213C3E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 48X60', 'Marmol_sintetico', 'GEN-61744062') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LVM BARI 63X48', 'Marmol_sintetico', 'GEN-0004BFB3') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 157X78', 'Fibra_de_vidrio', 'GEN-5BA1A6C0') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 130X78', 'Fibra_de_vidrio', 'GEN-D7B27131') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 148X90', 'Fibra_de_vidrio', 'GEN-68294632') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS RTM DERECHA 153X78', 'Fibra_de_vidrio', 'GEN-F24CF0C2') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS RTM IZQUIERDA 153X78', 'Fibra_de_vidrio', 'GEN-DD05727F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA BALI', 'Fibra_de_vidrio', 'GEN-4E792A5B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CALIMA 152X80 CON ANTIDESLIZANTE', 'Fibra_de_vidrio', 'GEN-81537FDD') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CALIMA 152X80 SIN ANTIDESLIZANTE', 'Fibra_de_vidrio', 'GEN-FC1B6BEB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ARRECIFE 152X90', 'Fibra_de_vidrio', 'GEN-F74EFA66') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ARRECIFE 183X90', 'Fibra_de_vidrio', 'GEN-4214D359') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BARU 152X152', 'Fibra_de_vidrio', 'GEN-03447CF2') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE DELTA 150X150', 'Fibra_de_vidrio', 'GEN-D4E6996C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ESPAÑOLA 170X75', 'Fibra_de_vidrio', 'GEN-B204A667') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE DELTA 130X130', 'Fibra_de_vidrio', 'GEN-D00FF343') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HEXAGONA 216X69', 'Fibra_de_vidrio', 'GEN-2E485741') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HAWAI ESQUINERA 150X150', 'Fibra_de_vidrio', 'GEN-D1537386') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE GALAPAGOS 250X200', 'Fibra_de_vidrio', 'GEN-C2747767') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 180X100', 'Fibra_de_vidrio', 'GEN-A626C651') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO RTM 150X8.5  BRILLANTE', 'Marmol_sintetico', 'GEN-FCAC0506') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X8.5 BRILLANTE', 'Marmol_sintetico', 'GEN-DD8FCCF8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 150X8 PLANO RTM', 'Marmol_sintetico', 'GEN-F1BD9D50') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X6 BRILLANTE', 'Marmol_sintetico', 'GEN-A1310E9E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X10 BRILLANTE', 'Marmol_sintetico', 'GEN-36BB749F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X5.3 BRILLANTE', 'Marmol_sintetico', 'GEN-C644C932') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON IBIZA', 'Fibra_de_vidrio', 'GEN-91C2F0F4') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PASAMANOS BAÑERA HAWAII', 'Fibra_de_vidrio', 'GEN-4A206BB2') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE TERRANOVA 183X113', 'Fibra_de_vidrio', 'GEN-BDC40CD1') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BALI', 'Fibra_de_vidrio', 'GEN-1EE9F586') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA SECADORA 50X40 MATE', 'Marmol_sintetico', 'GEN-A27E5718') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO LAVADORA 30X21 MATE', 'Marmol_sintetico', 'GEN-B5324827') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 60X60 MATE', 'Marmol_sintetico', 'GEN-E2277946') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REPISA LAVAMANOS 63X20 MATE', 'Marmol_sintetico', 'GEN-8F351DEB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE TAPA EXTENSION 60CM MATE', 'Marmol_sintetico', 'GEN-96FB977F') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SAHARA 48X41 MATE', 'Marmol_sintetico', 'GEN-33ABFDE9') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 80X60 MATE', 'Marmol_sintetico', 'GEN-3FF7C350') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS AQUA 40X35 MATE', 'Marmol_sintetico', 'GEN-27F46A14') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REGISTRO INSPECCION 65X45 MATE', 'Marmol_sintetico', 'GEN-F62E1C82') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS 46X46 MATE', 'Marmol_sintetico', 'GEN-16AE53CB') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 60X55', 'Marmol_sintetico', 'GEN-C9E01540') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE DUCHA 80X80 MATE', 'Marmol_sintetico', 'GEN-A5F86A7C') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE  DUCHA 90X90 MATE', 'Marmol_sintetico', 'GEN-507AF9FD') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 48X60 MATE', 'Marmol_sintetico', 'GEN-09DA40A8') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 90X60 MATE', 'Marmol_sintetico', 'GEN-AC490D60') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS DOHA VESSEL 45X33', 'Marmol_sintetico', 'GEN-D0D5C010') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS TRENTINO 63X48 BRILLANTE', 'Marmol_sintetico', 'GEN-0FF47D42') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS MECA VESSEL 35X35', 'Marmol_sintetico', 'GEN-74853E1E') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON LAVAMANOS OASIS 63X48', 'Marmol_sintetico', 'GEN-09D9D016') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS VERSA 50X50 BRILLANTE', 'Marmol_sintetico', 'GEN-058DDFB0') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS 48X51W BRILLANTE', 'Marmol_sintetico', 'GEN-83DF0A02') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVATRAPEROS PRO 46X36', 'Marmol_sintetico', 'GEN-43E4BCAD') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 60X60', 'Marmol_sintetico', 'GEN-E59A4DDF') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 48X43', 'Marmol_sintetico', 'GEN-4DB7918B') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 48X38', 'Marmol_sintetico', 'GEN-5BD9E14D') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 124X48', 'Marmol_sintetico', 'GEN-963DF57B') ON CONFLICT DO NOTHING;
COMMIT;
