-- PV_MOLDES V2.4
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS AMATISTA', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 66X51 SIN SALPICADERO', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 151X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 151X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DUCHA 115X70', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE COCINA MURANO 210X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE TAPA REGISTRO 30X30 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS VENECIA 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON LAVAMANOS OASIS 63X48 SOFT MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO NEVERA MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 60X51 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 50X50 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GAS MULTIPLE 53X15 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA LLAVE GAS 17X17 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO NEVERA BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO LAVADORA 30X21 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS ECO 30X30', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 60X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 46X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS CONSTRU 60X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REPISA LAVAMANOS 63X20 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REPISA LAVAMANOS 48X20 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SAHARA 47.5X40.5 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SAHARA 47.5X40.5 SOFT MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS IGUAZU 40X28 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 79X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 79X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 63X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS DAKAR 49X44 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OCEAN 48X43 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 94X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 63X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 79X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARCELONA 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS CORAL 41X37 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS ANKARA 43X43 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS ANIS 84X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS PETIT 38X38 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS MENTA 84X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS MANZANO 84X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS LAUREL 63X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS LAUREL 63X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS EMBASSY 100X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CEREZO 81X45 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CARRARA 50X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CARAMELO 81X45 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CANELO 55X43 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS ESPIGA 79X45 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE DUCHA 152X76 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 180X55', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE DUCHA 90X109 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS CIPRES 62X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON 100X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 100X51 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS AROMA 84X56 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS NOGAL 100X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO IBIZA 182X100', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA AQUA 150X60 V3 PERF CUBIERTA', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE GALAPAGOS 250X200 V.2', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA SANTORINI 180X180', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA 150X60 V.2 - PERF-CUB', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ESPAÑOLA 152X75', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS VIVE 60X50', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 160X90', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BONAIRE 183X152', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 150X8X4 RTM', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA HONOLULU DERECHA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS SIENA 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON SANTORINI PLUS 180X80', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MYDAS EMPOTRAR 182', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE NORUEGA 156', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA MALTA 160X80', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE QATAR 180X100', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON DANESA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 180X90X42', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA NORUEGA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA HONOLULU IZQUIERDA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON TAHITI 152X152', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON QATAR 180X100', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO FALDON SANTORINI PLUS 180X80', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CHATTANOOGAN 200X200', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE IBIZA 182X123', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CHALLENGER 190X190', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS IZQUIERDA 153X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS DERECHA 153X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE JAMAICA PLUS IZQUIERDA 152X75', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ITALIANA ECO 140X70', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SAVANNA 170X80X40', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 140X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON ECO 120X55 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA 180X60 SIN PERF V2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLACA PARA ENSAYOS 30X20 CM', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO  LAVAMANOS GENOVA 124X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON AMERICANA PLUS', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON AMERICANA PLUS EN L', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA RTM 180X60 V.2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO SALPICADERO 180X60 V.2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO SALPICADERO 150X60 V.2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
