-- PV_MOLDES V2.4
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS SIENA 155X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS GENOVA 155X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS IGUAZU 40X28', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVATRAPEROS ECO 30X30', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MYDAS 182', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 181X123', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BAÑERA MALTA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA VERSA 150X55  SIN PERF CUB', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO PLAQUITA PARA LVM GENOVA 79X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO  PLAQUITA PARA LVM GENOVA 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON MILENIUM LARGO', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON MILENIUM CORTO', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON COCINA 180X60 PERF-CUB V.2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO  LAVAPLATOS KOA 63X51 1 BOWL', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MEDIA ESFERA', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS GENOVA 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS VERSA 55X50', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 60X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 80X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 90X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 48X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LVM BARI 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 157X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 130X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA 148X90', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS RTM DERECHA 153X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS RTM IZQUIERDA 153X78', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA BALI', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CALIMA 152X80 CON ANTIDESLIZANTE', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CALIMA 152X80 SIN ANTIDESLIZANTE', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ARRECIFE 152X90', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ARRECIFE 183X90', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BARU 152X152', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE DELTA 150X150', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ESPAÑOLA 170X75', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE DELTA 130X130', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HEXAGONA 216X69', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HAWAI ESQUINERA 150X150', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE GALAPAGOS 250X200', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FRANCESA 180X100', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO RTM 150X8.5  BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X8.5 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 150X8 PLANO RTM', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X6 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X10 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ZOCALO 122X5.3 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON IBIZA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PASAMANOS BAÑERA HAWAII', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE TERRANOVA 183X113', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON BALI', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA SECADORA 50X40 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE CAJA GRIFO LAVADORA 30X21 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 60X60 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REPISA LAVAMANOS 63X20 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE TAPA EXTENSION 60CM MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SAHARA 48X41 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 80X60 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS AQUA 40X35 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE REGISTRO INSPECCION 65X45 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS 46X46 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 60X55', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE DUCHA 80X80 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PISO DE  DUCHA 90X90 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 48X60 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 90X60 MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS DOHA VESSEL 45X33', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS TRENTINO 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS MECA VESSEL 35X35', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO MESON LAVAMANOS OASIS 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS VERSA 50X50 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS 48X51W BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVATRAPEROS PRO 46X36', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVARROPAS AQUA 60X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 48X43', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 48X38', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 124X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
