-- PV_MOLDES V2.4
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS ECO 40X30', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 150X55 MATE SIN PERF', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 46X51', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 48X51W BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 155X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 120X55 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 60X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS TRENTINO 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 150X55 BRILLANTE SIN PERF', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 60X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 79X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 48X38', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON ECO 150X55 BRILLANTE PERF CUBIERTA', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS JOHAN VESSEL 50X40 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 80X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS ECO 48X38', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS VERSA 55X50', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS PRO 46X36', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 80X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 48X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 48X43', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 180X60 PERF-CUB V.2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS AQUA 90X60 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS PARMA 79X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BARRA COCINA 120X55 BRILLANTE - PERF-CUB', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS DOHA VESSEL 45X33 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS AQUA 40X35 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO DERECHO 140X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS KOA 84X56', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS PARMA 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE IBIZA 182X100', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO IZQUIERDO 100X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA SANTORINI 180X180 V.2', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 79X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 180X60 SIN PERF-CUB V.2', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 70X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS ECO 48X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 48X43 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 79X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 150X60 V.2 - PERF-CUB', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 124X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS KOA 63X51 1 BOWL', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS 50X50 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS VERSA 50X50 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS RIO 48X43 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 79X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO DERECHO 100X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA 150X60 V.2 SIN PERF', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON LAVAMANOS OASIS 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS MECA VESSEL 35X35 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS MECA VESSEL 35X35 SOFT MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO 60X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 48X43', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESA DE TRABAJO PRO-MESON 140X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS GENOVA 124X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 63X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS QUADRATTO 94X48 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVATRAPEROS 46X46 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA TAHITI 152X152', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS DOHA VESSEL 45X33 SOFT MATE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE JAMAICA PLUS DERECHA 152X75', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MOBU 200', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 124X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE DANESA 189X113X45', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BAÑERA CATALUÑA 170X90', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVARROPAS PRO IZQUIERDO 140X60', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HONOLULU DERECHA 180X120', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE HONOLULU IZQUIERDA 180X120', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO IBIZA 182X123', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MILENIUM 182X123', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 63X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE ITALIANA ECO 150X70', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE BARRA COCINA 120X55 BRILLANTE - SIN PERF', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE AMERICANA PLUS V.2', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE FALDON CATALUÑA', 'Fibra_de_vidrio', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MESON COCINA VERSA 150X55 SIN PERF CUB', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLAQUITA PARA LVM GENOVA 79X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLACA MUESTRAS', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLACA PARA MUESTRAS 20X20 CM', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS OSLO 94X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO BARRA COCINA 120X55 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MODELO LAVAMANOS ECO 48X38', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAPLATOS MOCA 84X51 BRILLANTE', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 150X55', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 180X55', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE PLACA GENOVA 124X48', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS BARI 100X50', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE MUESTRA COLORES', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS SIENA 120X51', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE LAVAMANOS OSLO 100X50', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
INSERT INTO public.tipos_moldes (molde_descripcion, planta, molde_sku) VALUES ('MOLDE SALPICADERO 61X10 PARA LVM', 'Marmol_sintetico', 'S/N') ON CONFLICT DO NOTHING;
